### ISSUE TITLE
Chybná výchozí hodnota consentu pro konverzi

### ISSUE THREAD

**Issue by jantichy** [pavelsabatka/gtm-sklik#4]
Když v nastavení tagu vyberu typ Conversion, bere tag defaultně informaci o consentu z analytics_storage. To je podle mě špatně, měl by ji brát defaultně z ad_storage. 

Navíc to na tu analytics_storage změní i u všech kontejnerů, které už dávno používaly předchozí verzi téhle šablony a teď si ji jen aktualizovaly. Což je strašně nepříjemné, protože tím se lidem najednou řídí nechtěně tenhle tag podle úplně jiných consentů, než dosud a než by měl, oni o tom vůbec nevědí – a pokud se v tom hluboce nehrabou, tak si toho ani vůbec nevšimnou.

(Doplňující poznámka, dělá to jen pro konverzi, když přepnu radiobutton na typ Retargeting, tak to bere správně ad_storage.)

**Comment by pavelsabatka** [comment]
Díky za upozornění, tohle jsem nastavil na ad_storage, update by měl být dostupný brzy v GTM.

**Comment by jantichy** [comment]
❤️ Děkujeme!
