### ISSUE TITLE
Retargeting - řešení spuštění kodu s consent = 0

### ISSUE THREAD

**Issue by PetrSuchan** [pavelsabatka/gtm-sklik#6]
Dobrý den, 

obracím se na vás s dotazem jak správně spustit retargeting s příznakem consent = 0. Seznam po nás nyní chtěl aby jsme jim zaslali retargeting i v případě, kdy uživatel nedal souhlas. Na straně seznamu by se takováto data měla zpracovat anonymně. Aktuálně jsem si toto vyřešil trochu krkolomně ale s požadovaným výsledkem. 

Na webu mám v datové vrstvě consent nový příznak consent_seznam. V šabloně jsem si založil nové pole consent_name_seznam a v něm consent_seznam. 
Následně v kodu jsem doplnil tento kod.

addConsentListener(data.consent_name_seznam, (consentType, granted) => {
      log('SKLIK RETARGETING: callback called, consent_name_seznam consent:', granted);
      if (consentType === data.consent_name_seznam && granted) {
        sendRemarketingHit(0);
      }
    });

Na webu v případě, kdy nemám povoleny cookies tak nastavím consent_seznam = 1 a spustím tuto akci. Seznamu to takto vyhovuje a má k dispozici data v anonymním režimu., po udělení souhlasu se okamžitě spustí značka se souhlasem. 

Přikládám šablonu jak jsem provedl úpravy

[Sklik_sabatka-upravena_ verze.zip](https://github.com/pavelsabatka/gtm-sklik/files/15345833/Sklik_sabatka-upravena_.verze.zip)

Děkuji za info
Petr

**Comment by pavelsabatka** [comment]
Dobrý den @PetrSuchan ,
díky za update.
Co se týká té šablony - její chování jsem 100 % řešil s dataři z Skliku a před spuštěním mi to ještě kontrolovali.
To, že se remarketingový hit neodesílá, bylo schválně - kvůli tomu, že ho Seznam nijak nevyužívá (nicméně ano, má to v dokumentaci).
Projdu tohle vlákno s manažery Seznamu a domluvím se s nimi, jak (a jestli) chování šablony upravit.

**Comment by pavelsabatka** [comment]
@PetrSuchan bavil jsem se s lidmi ze Seznam.cz, domluvili jsme se na tom, že přidáme posílání retargetingového hitu i bez souhlasu (s parametrem consent=0) - aby to bylo konzistentní s dokumentací.
Mrknu na zaslaný soubor a dořeším to.
Šablonu mi ale testují ještě lidi ze Seznam.cz, tak až to projde QA i za ně, tak to vydám.

**Comment by PetrSuchan** [comment]
Dobrý den, máte nějaký bližší termín? Stáhla se mi aktualizovaná šablona do GTM s datem 4.června ale nevidím v ní nějaké změny. Minimálně na webu se posílá stále špatně consent s 1 i když jsem ještě nedal souhlas.

**Comment by pavelsabatka** [comment]
> Minimálně na webu se posílá stále špatně consent s 1 i když jsem ještě nedal souhlas.
zvláštní. Jen pro ověření - používáte consent mode?
Můžete mi prosím případně poslat link na web, kde se to děje?

**Comment by pavelsabatka** [comment]
@PetrSuchan díval jsem se na uvedenou šablonu. Nicméně to vypadá jako nějaká starší verze. Zkuste prosím aktualizovat (ideálně z community gallery).

Uvedené updaty mám připravené, předal jsem je ještě na testování do Seznamu.

**Comment by pavelsabatka** [comment]
@PetrSuchan hity s consent=0 se posílají v aktualizované verzi
