### ISSUE TITLE
Použití Measurement Hub

### ISSUE THREAD

**Issue by Pepino483** [pavelsabatka/gtm-sklik#9]
Není tady chyba? https://github.com/pavelsabatka/gtm-sklik/blob/c1ecf971a553e22f6b48ceccb8932063b7f7b93a/template.tpl#L1093 Kontroluje se zda existuje data.category ale následně se používá data.page.category

**Comment by pavelsabatka** [comment]
@Pepino483 díky moc za upozornění.
Mám nachystaný nový release, během pár dní dám ven.

Btw. nějak používáš tenhle typ konfigurace? Jak jsi na to došel?

**Comment by Pepino483** [comment]
Posílám do GTM objekt podle toho co jsem vyčetl z kódu: `{page: {}, products: {}, user: {}}` a přišlo mi praktičtější vytvořit v GTM jen 3 proměnné než pro každou jednu hodnotu zvlášť. Je doporučené používat spíše variantu "Standard Variables"?

**Comment by pavelsabatka** [comment]
@Pepino483 je to jedno, fungovat bude oboje.
Jen s těmi objekty k tomu mám vlastní standard datové vrstvy, který je takhle navržen, tak mě zajímalo, jestli to ještě někdo takto používá :-)

Publikoval jsem upravenou verzi.

**Comment by Pepino483** [comment]
Máš k tomu standardu nějakou dokumentaci?

**Comment by pavelsabatka** [comment]
@Pepino483 ano, ale neveřejnou. Navíc k tomu mám dost skriptů v GTM. A smysl to dává jako celek.

Teoreticky to můžeme probrat, pokud se potkáme na nějaké akci nebo tak.

**Comment by pavelsabatka** [comment]
Jinak issue myslím můžeme uzavřít.
